### ISSUE TITLE
Size of database file

### ISSUE THREAD

**Issue by skrew** [objectbox/objectbox-swift#10]
Hi,

I have just tested your database library, it looks very promising.

However, the DB file size is 65% larger than our sqlite database (which contains indexes, unlike the Objectbox test db).
Is it because of the beta? Or is it because of the internal format of the DB ?

And, what is the max file size ? in the previous version, the app was crashing when DB file size > 1GB, but with the last release, the size seem to don't get higher than 1GB (and don't crash anymore). 

**Edit: Just tested again with multiple add/delete and finally, i still got the crash when i launch the app again:**
```[ERROR] Storage error "Cannot allocate memory" (code 12)```

Thanks

**Comment by uli-objectbox** [comment]
We currently optimize for performance over on-disk size, so that is to be expected for now. That said, we've prototyped approaches to compression that should reduce on-disk footprint in the future, alas that is not implemented yet.

For the file size limit, there is a max file size parameter that you pass to the `Store`. when you create it. Have you tried increasing that?

That crash should actually be a Swift exception (we just didn't implement a lot of exception handling in the example app), so you could catch that instead of crashing (I'll verify that it is, if it wasn't before, it should be in the next release).

As to file size limits, as we memory-map the database, the only hard limit should be your CPU's addressable memory (not physical, so usually ~48 bits).

**Comment by skrew** [comment]
Ok,
Any "compact on launch"-like command ? To reclaim space after multiple delete/insert ?

**Comment by uli-objectbox** [comment]
Not at the moment, no, but I'll make a ticket for it.

**Comment by skrew** [comment]
Ok thanks.
