### ISSUE TITLE
Preferred C API

### ISSUE THREAD

**Issue by drkibitz** [objectbox/objectbox-swift#4]
You said "let us know what you think", but not sure of the best place to do that. Really looking forward to trying this out, but not sure how or if I should yet.

Ideally, no Objective-C, and you can just have the C++ version back swift (C++ wrapped in a standard C api). This will allow the library to take full advantage of swift optimizations. Otherwise, it's just using the Objective-C runtime, and is an ergonomic choice.

**Comment by drkibitz** [comment]
Also, ideally, ObjectBox is the DB in the best position to take full advantage of swift value types. e.g. `EntityType` protocol does not necessarily have to adhere to `class`. Which means, since it is basically an atomic API, it would be totally boss to support reading and writing swift structs. 🙏

**Comment by uli-objectbox** [comment]
Thank you for your input. Agreed, Objective-C's requirement for classes in collections is an unfortunate limitation in our Swift API right now.

Just to make sure our future designs suit your needs, could you elaborate on your use-case? How are you using value types right now that make your database code easier (or where do you want solve a problem in your database model using value types, if you don't have an implementation yet)?

**Comment by jimisaacs** [comment]
@uli-objectbox we use https://github.com/ReSwift/ReSwift

There's a lot of different ways to use Redux (ReSwift), but ideally, I would love to be able to use value types in all of my models that I pass to the UI, and mutations go through the ReSwift flow, and I can simply put the updated struct "into the box" so to speak.

Basically, I'm not asking for objectbox to "copy on write" so to speak, but what I'm asking is since an entity is just a "box of fields", could the read/writer model support lets say a version of a `Codable`? Without a better way to describe it.

Codable supports structs or classes, because it is just an API that describes how to encode and decode and object's fields. I was thinking the same thing could happen with ObjectBox.

**Comment by drkibitz** [comment]
@uli-objectbox we use https://github.com/ReSwift/ReSwift

There's a lot of different ways to use Redux (ReSwift), but ideally, I would love to be able to use value types in all of my models that I pass to the UI, and mutations go through the ReSwift flow, and I can simply put the updated struct "into the box" so to speak.

Basically, I'm not asking for objectbox to support "copy on write" so to speak, but what I'm asking is since an entity is just a "box of fields", could the read/writer model support lets say a version of a Codable? Without a better way to describe it.

Codable supports structs or classes, because it is just an API that describes how to encode and decode an object's fields. I was thinking the same thing could happen with ObjectBox.

@uli-objectbox P.S. yes this comment is just like one posted by another user, would very much appreciate it if you just ignored that other comment and user ;)

**Comment by drkibitz** [comment]
@uli-objectbox thank you!

Also FYI, because I'm not sure of your plans, I would make a suggestion to what I think could be very clean API. Would if ObjectBox simply provided an implementation of Encoder/Decoder protocols?
- https://developer.apple.com/documentation/swift/encoder
- https://developer.apple.com/documentation/swift/decoder

Because a box already requires the type ref to be provided (from what I see in your Swift example on the website), `box.put(ob)` can be synonymous with `encoder.encode(ob)`, and `box.get(id)` can be synonymous with `decoder.decode(Type.self, data)`. Where `data` is how ever ObjextBox works internally to read data from `id`.

What this does, is keeps immutable structs and classes pure. All they need is to conform to Codable protocols. Not sure where this leaves `EntityType` though.

Base example I've seen that is a proof of concept:
https://github.com/elegantchaos/DictionaryCoding

**Comment by drkibitz** [comment]
@greenrobot Encoder/Decoder/Codable are all protocols. The only thing that is Apple’s other than the language, is the default implementation of JSONEncoder and JSONDecoder, which I avoided mentioning, and shared an open source example implementation instead.

You also hit on my point, ObjectBox already has an implementation so to speak, it just needs to conform, if not just internally, to the mentioned protocols to achieve an API that I described.

**Comment by uli-objectbox** [comment]
@drkibitz We've looked into Codable as a basis for storing objects before, but at the time found that encode() does not carry enough information.

I know it doesn't seem that way from the ObjectBox Swift SDK that you have in your hands right now, because it does not (yet) include the schema migration mechanisms we have in other languages, but when it does, we need to pass schema information while serializing an entity.

Without that additional information (that our code generator generates for you, initially), you wouldn't be able to rename entities and properties as easily as people are used to from ObjectBox.

Given our code generator creates all the serialization code for you (kind of like the Swift compiler special-cases Codable objects and generates their init/encode mehods under the hood), it should already feel as convenient as Codable does right now.

What advantages are you hoping to gain from ObjectBox going through Codable?

**Comment by drkibitz** [comment]
@uli-objectbox Thanks for getting back to me. After posting all of my info, I took a closer look at the lib and saw that you are using FlatBuffers, is that still correct? If so, I can see why the schema information is required, as order matters, something Codable doesn't give you.

What I was hoping for was a clean and fast implementation to persist the data behind Swift structs. If Codable isn't the answer that's fine, but if possible, would the codegen be able to support structs?

**Comment by uli-objectbox** [comment]
At the moment, as you noticed at the start of this thread, the use of Objective-C at the connecting point between Swift and C++ makes it difficult to support structs, but we're aware that this is an issue and are looking into ways to remedy that.

So, _technically yes, but not with the ObjectBox Swift SDK we have right now_ is the best I can say at the moment :)

**Comment by uli-objectbox** [comment]
Hi, we just released version 0.8.0 of ObjectBox Swift, where we rewrote a number of the Objective-C classes in Swift to enable struct support

We hope that this solves the issues you were experiencing using ObjectBox together with Redux/ReSwift. If there is anything else you need, feel free to get in touch and let us know.

**Comment by drkibitz** [comment]
This is great news! Looking forward to trying it out. So far the new docs are very clear.
